version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: trading-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: trading_pass
      POSTGRES_DB: trading
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: trading-backend
    restart: always
    depends_on:
      - db
    env_file:
      - ${ENV_FILE:-/etc/dokploy/env/indicadores-tecnicos.env}

    expose:
      - "8001" # 👈 solo expone a la red interna, no al host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trading-backend.rule=Host(`tradingdash.duckdns.org`)"
      - "traefik.http.routers.trading-backend.entrypoints=websecure"
      - "traefik.http.routers.trading-backend.tls.certresolver=myresolver"
      - "traefik.http.services.trading-backend.loadbalancer.server.port=8001"

networks:
  default:
    external: true
    name: dokploy-network

volumes:
  db_data:
